# Generated by Django 5.2 on 2026-01-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_portada',
        ),
    ]
